apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sergeybinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin  # Use cluster-admin for full access
subjects:
- kind: User
  name: skravec1@jh.edu  # User whom you are granting access
  apiGroup: rbac.authorization.k8s.io
